name: Repository Details 

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |       
       curl -i -u ${{secrets.Token}} https://api.github.com/KalpanaAddagada/Javawar/deployments
  
