name: Repository Details 

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |       
       curl -i -u username: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 https://api.github.com/KalpanaAddagada/Javawar/deployments
