name: COMMITS API

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
       { curl https://api.github.com/repos/pulipativedanth/sample-java-project/commits | jq '.[] | {Commit_id: .sha, Commit_Date: .commit.author.date, Commit_Author: .commit.author.name}'\ &&
       curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}';} >> "./output.json"
       #curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}'  >> "./output.json"
       #{ output=$ curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}'\ &&
       #curl https://api.github.com/repos/pulipativedanth/sample-java-project/commits | jq '.[] | {Commit_id: .sha, Commit_Date: .commit.author.date, Commit_Author: .commit.author.name}';} >> "./output.json"
       #curl \
       #-H "Accept: application/vnd.github.v3+json" \
       #https://api.github.com/repos/pulipativedanth/sample-java-project/commits
       echo "TAG_NAME=$(curl \
       -H "Accept: application/vnd.github.v3+json" \
       https://api.github.com/repos/pulipativedanth/sample-java-project/stats/participation | jq '.["all"] | add')" 
       echo "$TAG_NAME" 
    - name: Upload a Build Artifact
    - uses: actions/upload-artifact@v2.2.4
      with:
          name: artifact
          path: './output1.json'
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
          name: artifact
          path: './output1.json'
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      name: Azure Portal Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: fixpoint/azblob-upload-artifact@v4
      name: Upload Artifact to Blob Storage
      with:
       connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
       name: Blob
       path: './output.json'

   
