name: COMMITS API

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
       { curl https://api.github.com/repos/pulipativedanth/sample-java-project/commits | jq '.[] | {Commit_id: .sha, Commit_Date: .commit.author.date, Commit_Author: .commit.author.name}'\ &&
       curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}';} >> "./joutput.json"
       #curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}'  >> "./joutput.json"
       #{ joutput=$ curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}'\ &&
       #curl https://api.github.com/repos/pulipativedanth/sample-java-project/commits | jq '.[] | {Commit_id: .sha, Commit_Date: .commit.author.date, Commit_Author: .commit.author.name}';} >> "./joutput.json"
       #curl \
       #-H "Accept: application/vnd.github.v3+json" \
       #https://api.github.com/repos/pulipativedanth/sample-java-project/commits
       echo "TAG_NAME=$(curl \
       -H "Accept: application/vnd.github.v3+json" \
       https://api.github.com/repos/pulipativedanth/sample-java-project/stats/participation | jq '.["all"] | add')" 
       echo "$TAG_NAME" 
       
   
#     - name: Download a single artifact
#       uses: actions/download-artifact@v2
#       with:
#        name: artifact
#        path : './joutput3.json'
    - run: |
        cd /home/runner/work/sample-java-project/sample-java-project/
        ls -ltr
        echo "After "
        
#     - name: kamataryo__whoami
#       uses: kamataryo/whoami-action@v1
#     - uses: actions/checkout@v1
#     - uses: haythem/public-ip@v1.2
    - uses: azure/login@v1
      name: Azure Portal Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        cd /home/runner/work/sample-java-project/sample-java-project/
        ls -ltr
        echo "After "
    - uses: fixpoint/azblob-upload-artifact@v4
      name: Upload Artifact to Blob Storage
      with:
       connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
       name: Blob
       path: '/home/runner/work/sample-java-project/sample-java-project/joutput.json'
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: './joutput.json'
   
