name: COMMITS API

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |
       { curl https://api.github.com/repos/pulipativedanth/sample-java-project/commits | jq '.[] | {Commit_id: .sha, Commit_Date: .commit.author.date, Commit_Author: .commit.author.name}'\ &&
       curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}';} >> "./joutput.json"
       #curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}'  >> "./joutput.json"
       #{ joutput=$ curl -X GET https://api.github.com/repos/pulipativedanth/sample-java-project | jq -r '{Reponame: .name, Branch: .default_branch}'\ &&
       #curl https://api.github.com/repos/pulipativedanth/sample-java-project/commits | jq '.[] | {Commit_id: .sha, Commit_Date: .commit.author.date, Commit_Author: .commit.author.name}';} >> "./joutput.json"
       #curl \
       #-H "Accept: application/vnd.github.v3+json" \
       #https://api.github.com/repos/pulipativedanth/sample-java-project/commits
       echo "TAG_NAME=$(curl \
       -H "Accept: application/vnd.github.v3+json" \
       https://api.github.com/repos/pulipativedanth/sample-java-project/stats/participation | jq '.["all"] | add')" 
       echo "$TAG_NAME" 
       mkdir actions-runner && cd actions-runner
       #curl -o actions-runner-linux-x64-2.279.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.279.0/actions-runner-linux-x64-2.279.0.tar.gz
        echo "50d21db4831afe4998332113b9facc3a31188f2d0c7ed258abf6a0b67674413a  actions-runner-linux-x64-2.279.0.tar.gz" | shasum -a 256 -c
        tar xzf ./actions-runner-linux-x64-2.279.0.tar.gz
        ./config.sh --url https://github.com/pulipativedanth/sample-java-project --token ATGK2XMFKTSYUBD5WFJZ3PDBAKR6Q
        ./run.sh
       runs-on: self-hosted
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./joutput.json
    - name: Download a single artifact
      uses: actions/download-artifact@v2
      with:
       name: artifact
       path : './joutput3.json'
    - name: kamataryo__whoami
      uses: kamataryo/whoami-action@v1
    - uses: actions/checkout@v1
    - uses: haythem/public-ip@v1.2
    - uses: azure/login@v1
      name: Azure Portal Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: fixpoint/azblob-upload-artifact@v4
      name: Upload Artifact to Blob Storage
      with:
       connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
       name: Blob
       path: '/home/runner/work/sample-java-project/sample-java-project/*.json'

   
