name: API FOR ISSUES REQUEST

on:
  push:
    branches: [ master ]
jobs:

  curl:
    
    runs-on: ubuntu-latest
    steps:
    - name: curll
      run: |       
       curl https://api.github.com/repos/pulipativedanth/sample-java-project/actions/runs | jq '.[] | {Build_id: .workflow_runs[].id}' >> "./output.json"
        sed 's/}/},/g' ./output.json >> "./outputFinal.json"
        sed '$ s/.$//' ./outputFinal.json >> "./outputFinal2.json"
       
    - name: Upload a Test Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./outputFinal2.json
    - uses: azure/login@v1
      name: Azure Portal Login
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        cd /home/runner/work/sample-java-project/sample-java-project/
        ls -ltr
        echo "After "
    - uses: fixpoint/azblob-upload-artifact@v4
      name: Upload Artifact to Blob Storage
      with:
       connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
       name: Blob
       path: '/home/runner/work/sample-java-project/sample-java-project/outputFinal2.json'
    - uses: Azure/sql-action@v1
      name: SQL Insert Query to Export Data from JSON 
      with:
        server-name: githubactions.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './Database.dacpac'
        sql-file: ''
