# .github/workflows/sql-deploy.yml
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/sql-action@v1
      with:
        server-name: githubactions.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './Database.dacpac'
    - uses: Azure/mysql@v1
      with:
        server-name: githubactions.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        username: naveenlata
        password: Molina@2032
        database: githubactions/SQLGitHub
        sql-file: INSERT INTO dbo.ErrorLog VALUES (02/12/2062,'rajesh7',7,7,7,'test1',7,'test7')
   
   
