# .github/workflows/sql-deploy.yml
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/sql-action@v1
      with:
        server-name: githubactions.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './Database.dacpac'
    - uses: azure/sql-action@v1
      with:
        server-name: githubactions.database.windows.net
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: './query.sql'
        arguments: "-v ColValue1 = '${<!-- -->{ github.event.repository.name }}' ColValue2 = 'Test'  ColValue3= '${<!-- -->{ github.event.after }}' ColValue4 = '31-08-1994' ColValue5 = 'Test'"
 


    
       
   
   
