name: Repository Details 

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |       
       curl http://20.106.158.209:9000/api/measures/component?metricKeys=bugs,vulnerabilities,code_smells,coverage,tests,test_failures&component=sonar_dotnet | jq '.component.measures[] | { Total_Tests: .tests, Bugs: .bugs, coverage: .coverage, code_smells: .code_smells, Vulnerabilities: .vulnerabilities }'
      
