name: Sonarqube Metrics

on:
  push:
    branches: [ master ]

jobs:
 curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |       
       curl -u :779c6b984041f732a00d267f3c4f921645f7e601 'http://20.106.158.209:9000/api/measures/component?metricKeys=bugs&component=sonar_dotnet' >> "./output.json"
    - name: Upload a Test Artifact for Pull Request
      uses: actions/upload-artifact@v2.2.4
      with:
      # Artifact name
        name: artifact
        path: ./output.json
