name: Sonarqube Metrics

on:
  push:
    branches: [ master ]
jobs:

  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      run: |       
       curl -u Sonar_Token: http://20.106.158.209:9000/api/measures/component?metricKeys=bugs&component=sonar_dotnet
